# Generated by Django 2.1.1 on 2019-01-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=150)),
                ('stage_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('MAr', 'Married'), ('Sin', 'Single'), ('Div', 'Divorce'), ('com', 'Complicated')], max_length=10)),
                ('D_O_B', models.DateField()),
                ('record_label', models.CharField(max_length=100)),
                ('no_of_album', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('music_name', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('atist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=300)),
                ('Date', models.DateField()),
                ('status', models.CharField(choices=[('pub', 'publied'), ('Dra', 'Draft')], max_length=17)),
                ('post', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('video', models.FileField(upload_to='')),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=130)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Writer'),
        ),
    ]
