# Generated by Django 2.1.1 on 2019-01-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_weeklynews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='writer',
            new_name='name',
        ),
    ]
