# Generated by Django 2.1.1 on 2019-01-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190131_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='atist_name',
            new_name='artist_name',
        ),
    ]
