# Generated by Django 2.1.1 on 2019-01-31 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190131_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
