# Generated by Django 2.1.1 on 2019-01-31 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_music_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='no_of_album',
            new_name='No_of_Album',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='record_label',
            new_name='Record_Label',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='stage_name',
            new_name='Stage_Name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='surname',
            new_name='Surname',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='artist_name',
            new_name='Artist_Name',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='music',
            new_name='Music',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='music_name',
            new_name='Music_Name',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='release_date',
            new_name='Release_Date',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='post',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='artist',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='release_date',
            new_name='Release_Date',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='last_name',
            new_name='Surname',
        ),
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.AddField(
            model_name='news',
            name='Status',
            field=models.CharField(choices=[('pub', 'published'), ('Dra', 'Draft')], default=django.utils.timezone.now, max_length=17),
            preserve_default=False,
        ),
    ]
