# Generated by Django 2.1.1 on 2019-02-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190131_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='WeeklyNews',
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-Release_Date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-Release_Date']},
        ),
    ]
