# Generated by Django 2.1.1 on 2019-02-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190219_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-release_date']},
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='release_Date',
            new_name='release_date',
        ),
    ]
