# Generated by Django 2.1.1 on 2019-03-07 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190219_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
