# Generated by Django 2.1.1 on 2019-03-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190314_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='news',
        ),
    ]
